AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for dalr finance app
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties: &LambdaProperties
      Handler: src/lambda/getQuote/index.handler
      Runtime: nodejs14.x
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /quote
            Method: GET
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      <<: *LambdaProperties
      Handler: src/lambda/getTransactionHistory/index.handler
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /transaction-history
            Method: GET
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      <<: *LambdaProperties
      Handler: src/lambda/getUser/index.handler
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /user
            Method: GET
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      <<: *LambdaProperties
      Handler: src/lambda/postBuyStock/index.handler
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /buy
            Method: POST
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      <<: *LambdaProperties
      Handler: src/lambda/postCreateUser/index.handler
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /user
            Method: POST
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      <<: *LambdaProperties
      Handler: src/lambda/postFundAccount/index.handler
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /fund
            Method: POST
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      <<: *LambdaProperties
      Handler: src/lambda/postSellAccount/index.handler
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /sell
            Method: POST
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      <<: *LambdaProperties
      Handler: src/lambda/postWithdrawAccount/index.handler
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /withdraw
            Method: POST