version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::636793644820:user/aws-sam-cli-managed-build-dalr-api-pi-PipelineUser-924OOZ2PNUUA"

[build-dalr-api]
[build-dalr-api.pipeline_bootstrap]
[build-dalr-api.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::636793644820:role/aws-sam-cli-managed-build-da-PipelineExecutionRole-CVY34OVK3K2E"
cloudformation_execution_role = "arn:aws:iam::636793644820:role/aws-sam-cli-managed-build-CloudFormationExecutionR-1R0K6SUQ51BIK"
artifacts_bucket = "aws-sam-cli-managed-build-dalr-ap-artifactsbucket-9p2aog3ew4sn"
image_repository = ""
region = "us-west-2"

[deploy-dalr-api]
[deploy-dalr-api.pipeline_bootstrap]
[deploy-dalr-api.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::636793644820:role/aws-sam-cli-managed-deploy-d-PipelineExecutionRole-1UJCFBX5JUCKE"
cloudformation_execution_role = "arn:aws:iam::636793644820:role/aws-sam-cli-managed-deplo-CloudFormationExecutionR-CADOTUNL9RIB"
artifacts_bucket = "aws-sam-cli-managed-deploy-dalr-a-artifactsbucket-zrlwjd4si8yh"
image_repository = ""
region = "us-west-2"
